version: "2"
run:
  tests: true
linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - err113
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 15
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    godot:
      capital: true
    lll:
      line-length: 120
    nakedret:
      max-func-lines: 30
    nestif:
      min-complexity: 5
    nlreturn:
      block-size: 3
    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
        - name: unused-parameter
        - name: unreachable-code
        - name: constant-logical-expr
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - gochecknoglobals
          - gochecknoinits
          - lll
          - mnd
        path: _test\.go
      - linters:
          - mnd
        path: main\.go
      - linters:
          - gochecknoglobals
          - mnd
          - gochecknoinits
          - forbidigo
          - gocognit
          - goconst
          - revive
          - wrapcheck
          - gosec
          - lll
          - nestif
        path: cmd/
      - linters:
          - gci
        path: cmd/device.go
      - linters:
          - testpackage
          - goconst
          - gocognit
          - thelper
          - wrapcheck
          - revive
          - gosec
          - unparam
        path: tests/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
