package cmd

const (
	DarwinOS            = "darwin"
	StateBooted         = "Booted"
	StateShutdown       = "Shutdown"
	StateOffline        = "Offline"
	TypeIOSSimulator    = "iOS Simulator"
	TypeAndroidEmulator = "Android Emulator"
	PlatformIOS         = "ios"
	PlatformAndroid     = "android"
	NameIOS             = "iOS"
	NameAndroid         = "Android"
	ExtPNG              = ".png"
	ExtMP4              = ".mp4"
	ExtGIF              = ".gif"
	ExtAPK              = ".apk"
	ExtApp              = ".app"
	ExtIPA              = ".ipa"
	CmdXCrun            = "xcrun"
	CmdSimctl           = "simctl"
	CmdAdb              = "adb"
	CmdEmulator         = "emulator"
	CmdAvdManager       = "avdmanager"
	CmdFFmpeg           = "ffmpeg"
	CmdOsaScript        = "osascript"
	CmdXclip            = "xclip"
	CmdPlutil           = "plutil"
	PrefixScreenshot    = "screenshot"
	PrefixRecording     = "recording"
)
